import type { SortKey } from "./archive_helpers";
import { Search, SlidersHorizontal, X } from "lucide-react";

type Props = {
    searchQuery: string;
    onSearchQueryChange: (v: string) => void;

    // Keep these simple so they always match whatever the page decides
    typeOptions: string[];
    typeFilter: string; // "All" or "Weekly"/"Monthly"/"Quarterly"
    onTypeFilterChange: (v: string) => void;

    statusOptions: string[];
    statusFilter: string; // "All" or "Completed"/"In Progress"/"Failed"
    onStatusFilterChange: (v: string) => void;

    sortKey: SortKey;
    onSortKeyChange: (v: SortKey) => void;

    onClear: () => void;
};

export default function ArchiveFiltersBar(props: Props) {
    const {
        searchQuery,
        onSearchQueryChange,
        typeOptions,
        typeFilter,
        onTypeFilterChange,
        statusOptions,
        statusFilter,
        onStatusFilterChange,
        sortKey,
        onSortKeyChange,
        onClear,
    } = props;

    return (
        <div className="rounded-xl border border-gray-200 bg-white p-4 shadow-sm">
            <div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between">
                <div className="flex items-center gap-2">
                    <SlidersHorizontal className="h-4 w-4 text-[#193E6B]" />
                    <div className="text-sm font-semibold text-[#193E6B]">
                        Filters
                    </div>
                </div>

                <button
                    type="button"
                    onClick={onClear}
                    className="inline-flex items-center gap-2 self-start rounded-md border border-gray-200 bg-white px-3 py-2 text-xs font-semibold text-[#193E6B] hover:bg-gray-50 lg:self-auto"
                    title="Clear all filters"
                >
                    <X className="h-4 w-4" />
                    Clear
                </button>
            </div>

            <div className="mt-3 grid grid-cols-1 gap-3 lg:grid-cols-12">
                {/* Search */}
                <div className="lg:col-span-5">
                    <label className="text-xs font-semibold text-gray-600">
                        Search
                    </label>
                    <div className="mt-1 flex items-center gap-2 rounded-md border border-gray-200 bg-white px-3 py-2">
                        <Search className="h-4 w-4 text-gray-500" />
                        <input
                            value={searchQuery}
                            onChange={(e) =>
                                onSearchQueryChange(e.target.value)
                            }
                            placeholder="Report name, ID, generated by…"
                            className="w-full bg-transparent text-sm text-[#193E6B] outline-none placeholder:text-gray-400"
                        />
                    </div>
                </div>

                {/* Type */}
                <div className="lg:col-span-3">
                    <label className="text-xs font-semibold text-gray-600">
                        Type
                    </label>
                    <select
                        value={typeFilter}
                        onChange={(e) => onTypeFilterChange(e.target.value)}
                        className="mt-1 w-full rounded-md border border-gray-200 bg-white px-3 py-2 text-sm text-[#193E6B] outline-none hover:bg-gray-50"
                    >
                        <option value="All">All</option>
                        {typeOptions.map((t) => (
                            <option key={t} value={t}>
                                {t}
                            </option>
                        ))}
                    </select>
                </div>

                {/* Status */}
                <div className="lg:col-span-2">
                    <label className="text-xs font-semibold text-gray-600">
                        Status
                    </label>
                    <select
                        value={statusFilter}
                        onChange={(e) => onStatusFilterChange(e.target.value)}
                        className="mt-1 w-full rounded-md border border-gray-200 bg-white px-3 py-2 text-sm text-[#193E6B] outline-none hover:bg-gray-50"
                    >
                        <option value="All">All</option>
                        {statusOptions.map((s) => (
                            <option key={s} value={s}>
                                {s}
                            </option>
                        ))}
                    </select>
                </div>

                {/* Sort */}
                <div className="lg:col-span-2">
                    <label className="text-xs font-semibold text-gray-600">
                        Sort
                    </label>
                    <select
                        value={sortKey}
                        onChange={(e) =>
                            onSortKeyChange(e.target.value as SortKey)
                        }
                        className="mt-1 w-full rounded-md border border-gray-200 bg-white px-3 py-2 text-sm text-[#193E6B] outline-none hover:bg-gray-50"
                    >
                        <option value="generated_desc">
                            Generated (newest)
                        </option>
                        <option value="generated_asc">
                            Generated (oldest)
                        </option>
                        <option value="name_asc">Name (A–Z)</option>
                        <option value="name_desc">Name (Z–A)</option>
                        <option value="type_asc">Type (A–Z)</option>
                        <option value="type_desc">Type (Z–A)</option>
                        <option value="status_asc">Status (A–Z)</option>
                        <option value="status_desc">Status (Z–A)</option>
                    </select>
                </div>
            </div>
        </div>
    );
}
