import { Link } from "react-router";
import {
    CalendarClock,
    CalendarDays,
    CalendarRange,
    CheckCircle2,
    AlertCircle,
    Loader2,
    Eye,
    Download,
    Copy,
    Link2,
} from "lucide-react";
import { motion } from "framer-motion";
import { toast } from "sonner";

import { cn } from "../../utils/cn";
import {
    badgeClass,
    formatGeneratedOn,
    typePillClass,
} from "./archive_helpers";

type ReportSummary = {
    id: string;
    name: string;
    periodLabel: string;
    generatedOn: string;
    generatedBy: string;
    type: string;
    status: string;
};

type Props = {
    reports: ReportSummary[];
};

function TypeIcon({ type }: { type: string }) {
    if (type === "Weekly")
        return <CalendarClock className="h-4 w-4 text-[#193E6B]" />;
    if (type === "Monthly")
        return <CalendarDays className="h-4 w-4 text-[#193E6B]" />;
    if (type === "Quarterly")
        return <CalendarRange className="h-4 w-4 text-[#193E6B]" />;
    return <CalendarDays className="h-4 w-4 text-[#193E6B]" />;
}

function StatusIcon({ status }: { status: string }) {
    if (status === "Completed") return <CheckCircle2 className="h-4 w-4" />;
    if (status === "Failed") return <AlertCircle className="h-4 w-4" />;
    if (status === "In Progress")
        return <Loader2 className="h-4 w-4 animate-spin" />;
    return <CheckCircle2 className="h-4 w-4" />;
}

function buildExecutiveSummaryPath(reportId: string) {
    return `/preview/executive-summary?reportId=${encodeURIComponent(reportId)}`;
}

function buildAbsoluteUrl(path: string) {
    if (typeof window === "undefined") return path;
    return `${window.location.origin}${path}`;
}

export default function ArchiveReportsTable(props: Props) {
    const { reports } = props;

    function handleCopyLink(reportId: string) {
        const path = buildExecutiveSummaryPath(reportId);
        const url = buildAbsoluteUrl(path);

        if (navigator?.clipboard?.writeText) {
            navigator.clipboard
                .writeText(url)
                .then(() => toast.success("Report link copied"))
                .catch(() =>
                    toast.info("Copy failed", {
                        description:
                            "Please copy the link manually from the address bar.",
                    })
                );
        } else {
            toast.info("Copy not supported", {
                description:
                    "Please copy the link manually from the address bar.",
            });
        }
    }

    function handleDownloadMock(reportName: string) {
        toast.info("Download is coming soon (mockup)", {
            description: `Export will be enabled later. (${reportName})`,
        });
    }

    function handleDuplicateMock(reportName: string) {
        toast("Template loaded", {
            description: `${reportName} (mock duplicate flow)`,
        });
    }

    return (
        <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.22 }}
            className="rounded-xl border border-gray-200 bg-white shadow-sm"
        >
            <div className="flex items-center justify-between px-5 py-4">
                <div>
                    <div className="text-base font-semibold text-[#193E6B]">
                        Report archive
                    </div>
                    <p className="mt-1 text-sm text-gray-600">
                        Search, filter, and open historical reports for
                        comparison and reference.
                    </p>
                </div>

                <div className="text-xs text-gray-500">
                    Showing{" "}
                    <span className="font-semibold text-[#193E6B]">
                        {reports.length}
                    </span>
                </div>
            </div>

            <div className="max-h-[520px] overflow-auto border-t border-gray-200">
                <table className="w-full text-left text-sm">
                    <thead className="sticky top-0 bg-white">
                        <tr className="text-xs uppercase tracking-wide text-gray-500">
                            <th className="px-5 py-3">Report</th>
                            <th className="px-5 py-3">Period</th>
                            <th className="px-5 py-3">Generated On</th>
                            <th className="px-5 py-3">Generated By</th>
                            <th className="px-5 py-3">Type</th>
                            <th className="px-5 py-3">Status</th>
                            <th className="px-5 py-3">Actions</th>
                        </tr>
                    </thead>

                    <tbody>
                        {reports.map((r, idx) => (
                            <motion.tr
                                key={r.id}
                                initial={{ opacity: 0, y: 6 }}
                                animate={{ opacity: 1, y: 0 }}
                                transition={{
                                    duration: 0.18,
                                    delay: Math.min(idx * 0.015, 0.2),
                                }}
                                whileHover={{ y: -1 }}
                                className="border-t border-gray-100 hover:bg-[#193E6B]/[0.03]"
                            >
                                <td className="px-5 py-3">
                                    <div className="font-semibold text-[#193E6B]">
                                        {r.name}
                                    </div>
                                    <div className="text-xs text-gray-500">
                                        {r.id}
                                    </div>
                                </td>

                                <td className="px-5 py-3 text-gray-700">
                                    {r.periodLabel}
                                </td>

                                <td className="px-5 py-3 text-gray-700">
                                    {formatGeneratedOn(r.generatedOn)}
                                </td>

                                <td className="px-5 py-3 text-gray-700">
                                    {r.generatedBy}
                                </td>

                                <td className="px-5 py-3">
                                    <span
                                        className={`${typePillClass()} gap-2`}
                                    >
                                        <TypeIcon type={r.type} />
                                        {r.type}
                                    </span>
                                </td>

                                <td className="px-5 py-3">
                                    <span
                                        className={cn(
                                            "inline-flex items-center gap-2 rounded-full px-2 py-1 text-xs font-semibold",
                                            badgeClass(r.status)
                                        )}
                                    >
                                        <StatusIcon status={r.status} />
                                        {r.status}
                                    </span>
                                </td>

                                <td className="px-5 py-3">
                                    <div className="flex flex-wrap items-center gap-2">
                                        <Link
                                            to={buildExecutiveSummaryPath(r.id)}
                                            className={cn(
                                                "inline-flex items-center gap-2 rounded-md border border-gray-200 bg-white px-3 py-2 text-xs font-semibold",
                                                "text-[#193E6B] hover:bg-gray-50"
                                            )}
                                            title="Open Executive Summary"
                                            onClick={() =>
                                                toast("Opening report…", {
                                                    description: r.name,
                                                })
                                            }
                                        >
                                            <Eye className="h-4 w-4" />
                                            Preview
                                        </Link>

                                        <button
                                            type="button"
                                            onClick={() => handleCopyLink(r.id)}
                                            className={cn(
                                                "inline-flex items-center gap-2 rounded-md border border-gray-200 bg-white px-3 py-2 text-xs font-semibold",
                                                "text-[#193E6B] hover:bg-gray-50"
                                            )}
                                            title="Copy report link"
                                        >
                                            <Link2 className="h-4 w-4 text-[#193E6B]/70" />
                                            Copy link
                                        </button>

                                        <button
                                            type="button"
                                            onClick={() =>
                                                handleDownloadMock(r.name)
                                            }
                                            className={cn(
                                                "inline-flex items-center gap-2 rounded-md border border-gray-200 bg-white px-3 py-2 text-xs font-semibold",
                                                "text-[#193E6B] hover:bg-gray-50"
                                            )}
                                            title="Download is coming soon (mockup)"
                                        >
                                            <Download className="h-4 w-4 text-[#193E6B]/70" />
                                            PDF
                                        </button>

                                        <Link
                                            to={`/generate?templateReportId=${encodeURIComponent(r.id)}`}
                                            className={cn(
                                                "inline-flex items-center gap-2 rounded-md border border-[#B3A125]/35 bg-[#B3A125]/10 px-3 py-2 text-xs font-semibold",
                                                "text-[#193E6B] hover:bg-[#B3A125]/15"
                                            )}
                                            title="Duplicate this report setup (mock)"
                                            onClick={() =>
                                                handleDuplicateMock(r.name)
                                            }
                                        >
                                            <Copy className="h-4 w-4" />
                                            Duplicate
                                        </Link>
                                    </div>
                                </td>
                            </motion.tr>
                        ))}

                        {reports.length === 0 && (
                            <tr>
                                <td
                                    className="px-5 py-6 text-sm text-gray-600"
                                    colSpan={7}
                                >
                                    No reports match your current filters.
                                </td>
                            </tr>
                        )}
                    </tbody>
                </table>
            </div>
        </motion.div>
    );
}
