// app/pages/home/recent_reports_table.tsx
import { Link } from "react-router";
import { reportSummaries } from "../../data/mockReportSummaries";
import { Clock, Archive, ArrowRight, Copy, Download } from "lucide-react";
import { toast } from "sonner";
import { badgeClass, formatGeneratedOn, typePillClass } from "./home_helpers";

function buildExecutiveSummaryUrl(reportId: string) {
    return `/preview/executive-summary?reportId=${encodeURIComponent(reportId)}`;
}

export default function RecentReportsTable() {
    function handleCopyLink(reportId: string) {
        const url =
            typeof window !== "undefined"
                ? `${window.location.origin}${buildExecutiveSummaryUrl(reportId)}`
                : buildExecutiveSummaryUrl(reportId);

        // Clipboard API with fallback toast
        if (navigator?.clipboard?.writeText) {
            navigator.clipboard
                .writeText(url)
                .then(() => toast.success("Report link copied"))
                .catch(() =>
                    toast.info("Copy failed", {
                        description:
                            "Please copy the link manually from the address bar.",
                    })
                );
        } else {
            toast.info("Copy not supported in this browser", {
                description:
                    "Please copy the link manually from the address bar.",
            });
        }
    }

    function handleDownloadMock() {
        toast.info("Download is coming soon (mockup)", {
            description:
                "Export will be enabled after generation logic is finalized.",
        });
    }

    return (
        <div className="rounded-xl border border-gray-200 bg-white shadow-sm">
            <div className="flex items-center justify-between px-5 py-4">
                <div>
                    <div className="flex items-center gap-2">
                        <Clock className="h-4 w-4 text-[#193E6B]" />
                        <h2 className="text-base font-semibold text-[#193E6B]">
                            Recent reports
                        </h2>
                    </div>
                    <p className="mt-1 text-sm text-gray-600">
                        Quick access to your most recently generated reports.
                    </p>
                </div>

                <Link
                    to="/archive"
                    className="inline-flex items-center gap-2 rounded-md border border-[#B3A125]/35 bg-[#B3A125]/10 px-3 py-2 text-sm font-semibold text-[#193E6B] hover:bg-[#B3A125]/15"
                >
                    <Archive className="h-4 w-4" />
                    View Archive
                </Link>
            </div>

            <div className="max-h-[420px] overflow-auto border-t border-gray-200">
                <table className="w-full text-left text-sm">
                    <thead className="sticky top-0 bg-white">
                        <tr className="text-xs uppercase tracking-wide text-gray-500">
                            <th className="px-5 py-3">Report Name</th>
                            <th className="px-5 py-3">Period</th>
                            <th className="px-5 py-3">Generated On</th>
                            <th className="px-5 py-3">Generated By</th>
                            <th className="px-5 py-3">Type</th>
                            <th className="px-5 py-3">Status</th>
                            <th className="px-5 py-3 text-right">Actions</th>
                        </tr>
                    </thead>

                    <tbody>
                        {reportSummaries.map((r) => (
                            <tr
                                key={r.id}
                                className="border-t border-gray-100 hover:bg-[#193E6B]/[0.03]"
                            >
                                <td className="px-5 py-3">
                                    <Link
                                        to={buildExecutiveSummaryUrl(r.id)}
                                        className="font-semibold text-[#193E6B] hover:underline"
                                        onClick={() =>
                                            toast("Opening report…", {
                                                description: r.name,
                                            })
                                        }
                                    >
                                        {r.name}
                                    </Link>
                                    <div className="text-xs text-gray-500">
                                        {r.id}
                                    </div>
                                </td>

                                <td className="px-5 py-3 text-gray-700">
                                    {r.periodLabel}
                                </td>

                                <td className="px-5 py-3 text-gray-700">
                                    {formatGeneratedOn(r.generatedOn)}
                                </td>

                                <td className="px-5 py-3 text-gray-700">
                                    {r.generatedBy}
                                </td>

                                <td className="px-5 py-3">
                                    <span className={typePillClass()}>
                                        {r.type}
                                    </span>
                                </td>

                                <td className="px-5 py-3">
                                    <span
                                        className={`inline-flex items-center rounded-full px-2 py-1 text-xs font-semibold ${badgeClass(
                                            r.status
                                        )}`}
                                    >
                                        {r.status}
                                    </span>
                                </td>

                                <td className="px-5 py-3">
                                    <div className="flex items-center justify-end gap-2">
                                        <Link
                                            to={buildExecutiveSummaryUrl(r.id)}
                                            className="inline-flex items-center gap-2 rounded-md border border-gray-200 bg-white px-3 py-2 text-xs font-semibold text-[#193E6B] hover:bg-gray-50"
                                            title="Open Executive Summary"
                                        >
                                            <ArrowRight className="h-4 w-4 text-[#B3A125]" />
                                            Open
                                        </Link>

                                        <button
                                            type="button"
                                            onClick={() => handleCopyLink(r.id)}
                                            className="inline-flex items-center gap-2 rounded-md border border-gray-200 bg-white px-3 py-2 text-xs font-semibold text-[#193E6B] hover:bg-gray-50"
                                            title="Copy report link"
                                        >
                                            <Copy className="h-4 w-4 text-[#193E6B]/70" />
                                            Copy
                                        </button>

                                        <button
                                            type="button"
                                            onClick={handleDownloadMock}
                                            className="inline-flex items-center gap-2 rounded-md border border-gray-200 bg-white px-3 py-2 text-xs font-semibold text-[#193E6B] hover:bg-gray-50"
                                            title="Download (mock)"
                                        >
                                            <Download className="h-4 w-4 text-[#193E6B]/70" />
                                            PDF
                                        </button>
                                    </div>
                                </td>
                            </tr>
                        ))}

                        {reportSummaries.length === 0 && (
                            <tr>
                                <td
                                    className="px-5 py-6 text-sm text-gray-600"
                                    colSpan={7}
                                >
                                    No reports available yet. Generate your
                                    first report to populate this list.
                                </td>
                            </tr>
                        )}
                    </tbody>
                </table>
            </div>
        </div>
    );
}
